# Dependencies
highlighter:      rouge
remote_theme: mmistakes/minimal-mistakes

# Permalinks
permalink:        pretty

# Setup
title:            blueCFD-Core Project
tagline:          'Enabling native use of OpenFOAM&reg; on Windows'
description:      'Bringing OpenFOAM&reg; technology to Windows.'
url:              https://blueCFD.github.io
baseurl:          /Core

author:
  name:           'FS Dynamics Portugal'
  url:            https://fsdynamics.pt
  email:          http://bluecfd.com/contact

paginate:         3
paginate_path:    "/News/page:num/"

# Custom vars
version:          2024-1

github:
  repo:           https://github.com/blueCFD/Core
