# Dependencies
highlighter:      rouge
remote_theme: fongandrew/hydeout

# Permalinks
permalink:        pretty

# Setup
title:            blueCFD-Core Project
tagline:          'Enabling native use of OpenFOAM&reg; on Windows'
description:      'Bringing OpenFOAM&reg; technology to Windows.'
url:              https://blueCFD.github.io
baseurl:          https://blueCFD.github.io/Core

author:
  name:           'FSD blueCAPE Lda'
  url:            http://www.bluecape.com.pt
  email:          http://bluecfd.com/contact

paginate:         3
paginate_path:    "/News/page:num/"

# Custom vars
version:          2020-1

github:
  repo:           https://github.com/blueCFD/Core
